packages:
  - packages/*

allowedDeprecatedVersions: {}

autoInstallPeers: true

dedupePeerDependents: true

gitChecks: true

ignoreScripts: false

ignoredOptionalDependencies: []

linkWorkspacePackages: true

nodeLinker: isolated

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx

overrides: {}

packageExtensions: {}

patchedDependencies: {}

peerDependencyRules:
  allowedVersions: {}
  ignoreMissing: []

resolutionMode: highest

resolvePeersFromWorkspaceRoot: true

saveWorkspaceProtocol: rolling

sharedWorkspaceLockfile: true

strictPeerDependencies: false

symlink: true
